version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      -checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
      - run:
          name: Test e2e
          command: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
      - run:
          name: Build
          command: npm run build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  