version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Test
          command: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
      - run:
          name: Test e2e
          command: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
      - run:
          name: Generate code coverage
          command: "./node_modules/.bin/nyc report --reporter=text-lcov"
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/mazeflix
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths: mazeflix/dist
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
  deploy:
    steps:
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
